version: "3"
services:
  tomcat1:
    image: tomcat:7-jre8
    container_name: tomcat1
    expose:
      - "8009"
    networks:
     - production-network
    volumes:
     - ./Tomcats/Tomcat1/projeto.war:/usr/local/tomcat/webapps/projeto.war
     - ./Tomcats/Tomcat1/server.xml:/usr/local/tomcat/conf/server.xml

  tomcat2:
    image: tomcat:7-jre8
    container_name: tomcat2
    expose:
      - "8009"
    networks:
     - production-network
    volumes:
     - ./Tomcats/Tomcat2/projeto.war:/usr/local/tomcat/webapps/projeto.war
     - ./Tomcats/Tomcat2/server.xml:/usr/local/tomcat/conf/server.xml

  tomcat3:
    image: tomcat:7-jre8
    container_name: tomcat3
    expose:
      - "8009"
    networks:
     - production-network
    volumes:
     - ./Tomcats/Tomcat3/projeto.war:/usr/local/tomcat/webapps/projeto.war
     - ./Tomcats/Tomcat3/server.xml:/usr/local/tomcat/conf/server.xml

  httpd:
    container_name: servidor
    expose:
      - "80"
    volumes:
      - ./logs:/var/log/apache2
    build: httpd/.
    image: brunocroh/httpd-modjk
    networks:
      - production-network
    depends_on: 
      - "tomcat1"
      - "tomcat2"
      - "tomcat3"

networks:
  production-network:
    driver: bridge
