version: '3'
services:
  web1:
    container_name: web1
    build: tomcat1/.
  web2:
    container_name: web2
    build: tomcat2/.
  web3:
    container_name: web3
    build: tomcat3/.
  httpd:
    volumes:
      - ./logs:/var/log/apache2
    ports:
      - 80
    build: httpd/.
